version: "3.9"
services:
  ide:
    build: .
    ports:
      - "8887:8887"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /share:/share
      - ide-state:/root
    environment:
      - PROJECTOR_USER_NAME=root
    user: root
      

volumes:
  ide-state: